fields:
  EMAIL:
  - ^[\w\.-]+@[\w\.-]+\.\w{2,}$
  DATE:
  - \b(?:\d{4}[-/.]\d{2}[-/.]\d{2}|\d{2}[-/.]\d{2}[-/.]\d{4}|\d{8}|\d{2}/\d{2}/\d{4}|\d{2}\s(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s\d{4}|\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s\d{1,2},\s\d{4})\b
  PHONE:
  - \B(?:\+1\s?)?(?:\(?\d{3}\)?[\s.-]?)\d{3}[\s.-]?\d{4}\b
  - \(?\b[0-9]{3}\)?[-.\s]?[0-9]{3}[-.\s]?[0-9]{4}\b  
  SSN:
  - \b\d{3}-\d{2}-\d{4}\b
  PERSON:
  - \b[A-Z][a-z]+(?:\s[A-Z]\.)?\s[A-Z][a-z]+(?:\s[A-Z][a-z]+)*\b
  - \b[A-Z]+(?:\s[A-Z]\.)?\s[A-Z]+(?:\s[A-Z]+)*\b
  ACCOUNT_NUMBER:
  - \b\d{5,}\b
  MONEY:
  - \$\d{1,3}(,\d{3})*(\.\d{2})?
  ADDRESS:
  - \b\d{1,5}\s[A-Za-z]+(?:\s[A-Za-z]+)*\s(?:Street|St|Avenue|Ave|Road|Rd|Lane|Ln|Boulevard|Blvd|Drive|Dr|Court|Ct|Place|Pl)\b

